<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ItemsTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now()->toDateTimeString();

        $items = [
            // Sepatu / footwear
            [
                'item_name' => 'Sepatu Gunung Eiger Plum 2.0',
                'description' => 'Sepatu hiking mid cut dengan sol anti slip dan bahan tahan air.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 25000,
                'sale_price' => 25000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sepatu Gunung Eiger Lynk',
                'description' => 'Sepatu hiking tangguh untuk jalur ekstrem.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 25000,
                'sale_price' => 25000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sepatu Gunung Rubtrack',
                'description' => 'Sepatu gunung dengan grip kuat dan desain stylish.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 25000,
                'sale_price' => 25000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sepatu Gunung Teon',
                'description' => 'Sepatu ringan dan fleksibel untuk jalur lembab.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 25000,
                'sale_price' => 25000,
                'rental_stock' => 2,
                'sale_stock' => 2,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sepatu Gunung Abu-Abu',
                'description' => 'Sepatu serbaguna untuk hiking santai.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 20000,
                'sale_price' => 20000,
                'rental_stock' => 4,
                'sale_stock' => 4,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sandal Gunung Eiger',
                'description' => 'Sandal outdoor dengan grip kuat dan tali adjustable.',
                'category' => 'Sepatu',
                'url_image' => null,
                'rental_price_per_day' => 15000,
                'sale_price' => 15000,
                'rental_stock' => 5,
                'sale_stock' => 5,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tenda
            [
                'item_name' => 'Tenda Camping',
                'description' => 'Tenda ringan untuk 2–3 orang dengan ventilasi ganda.',
                'category' => 'Tenda',
                'url_image' => null,
                'rental_price_per_day' => 35000,
                'sale_price' => 35000,
                'rental_stock' => 2,
                'sale_stock' => 2,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Jaket
            [
                'item_name' => 'Jaket Hitam Outdoor',
                'description' => 'Jaket tahan air dengan lapisan breathable dan saku dalam.',
                'category' => 'Jaket',
                'url_image' => null,
                'rental_price_per_day' => 30000,
                'sale_price' => 30000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Tas / carrier
            [
                'item_name' => 'Carrier Eiger Streamline',
                'description' => 'Tas gunung 40L dengan bantalan punggung empuk.',
                'category' => 'Tas',
                'url_image' => null,
                'rental_price_per_day' => 40000,
                'sale_price' => 40000,
                'rental_stock' => 2,
                'sale_stock' => 2,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Carrier Cosavior',
                'description' => 'Carrier besar dengan rain cover dan strap adjustable.',
                'category' => 'Tas',
                'url_image' => null,
                'rental_price_per_day' => 40000,
                'sale_price' => 40000,
                'rental_stock' => 2,
                'sale_stock' => 2,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Carrier Streamline Bagian Belakang',
                'description' => 'Tampilan belakang carrier streamline untuk ventilasi ekstra.',
                'category' => 'Tas',
                'url_image' => null,
                'rental_price_per_day' => 40000,
                'sale_price' => 40000,
                'rental_stock' => 1,
                'sale_stock' => 1,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Perlengkapan hiking
            [
                'item_name' => 'Headlamp Antarestar',
                'description' => 'Headlamp terang dengan mode fokus dan flood.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 10000,
                'sale_price' => 10000,
                'rental_stock' => 4,
                'sale_stock' => 4,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Headlamp BigAdventure',
                'description' => 'Lampu kepala ringan dan tahan air untuk aktivitas malam.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 10000,
                'sale_price' => 10000,
                'rental_stock' => 4,
                'sale_stock' => 4,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Botol Minum Eiger',
                'description' => 'Botol 1L kuat dan tahan banting untuk kegiatan outdoor.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 15000,
                'sale_price' => 15000,
                'rental_stock' => 6,
                'sale_stock' => 6,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Celana Gunung',
                'description' => 'Celana outdoor ringan dan cepat kering.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 20000,
                'sale_price' => 20000,
                'rental_stock' => 4,
                'sale_stock' => 4,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Kaos Kaki Oren',
                'description' => 'Kaos kaki nyaman untuk hiking.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 5000,
                'sale_price' => 5000,
                'rental_stock' => 10,
                'sale_stock' => 10,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Trekking Pole',
                'description' => 'Tongkat pendakian ringan dan kuat untuk stabilitas.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 15000,
                'sale_price' => 15000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'item_name' => 'Sleeping Bag Hijau',
                'description' => 'Sleeping bag hangat untuk suhu dingin di gunung.',
                'category' => 'Perlengkapan',
                'url_image' => null,
                'rental_price_per_day' => 25000,
                'sale_price' => 25000,
                'rental_stock' => 3,
                'sale_stock' => 3,
                'penalty_per_days' => 0.00,
                'is_rentable' => 1,
                'is_sellable' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('items')->insert($items);
    }
}
